#ifndef _SCATS_VERSION_H_
#define _SCATS_VERSION_H_

#define SCATS_VERSION_MAJOR 0
#define SCATS_VERSION_MINOR 1
#define SCATS_VERSION_REVISION 0

#define SCATS_TO_STRING_HELPER(x) #x
#define SCATS_TO_STRING(x) SCATS_TO_STRING_HELPER(x)

#define SCATS_VERSION_STRING              \
     SCATS_TO_STRING(SCATS_VERSION_MAJOR) \
     "." SCATS_TO_STRING(SCATS_VERSION_MINOR) "." SCATS_TO_STRING(SCATS_VERSION_REVISION)

#endif